#!/usr/bin/env python3
from pathlib import Path
import argparse
import hashlib
import json
import re
import subprocess
import tarfile
import zipfile

ROOT = Path(__file__).resolve().parents[1]
REQUIRED_PLUGIN_FILES = [
    "Info.json",
    "main.js",
    "global.js",
    "overlay.html",
    "dictionary-manager.html",
    "preferences.html",
    "README.md",
    "THIRD_PARTY_NOTICES.md",
    "native-dependencies.lock.json",
    "LICENSE",
    "package.json",
]
OPTIONAL_PACKAGE_FILES = [
    "ARCHITECTURE.md",
    "MAINTAINABILITY_AUDIT.md",
    "SETTINGS_AUDIT.md",
]
REQUIRED_PACKAGE_FILES = REQUIRED_PLUGIN_FILES + [
    "CHANGELOG.md",
    "bin/iina-hoshi-dicts",
]
PACKAGE_FILE_ALLOWLIST = REQUIRED_PACKAGE_FILES + OPTIONAL_PACKAGE_FILES
NATIVE_LICENSE_FILES = {
    "THIRD_PARTY_LICENSES/FFmpeg-LGPL-2.1.txt": "build/native-geometry-deps/sources/FFmpeg/COPYING.LGPLv2.1",
    "THIRD_PARTY_LICENSES/FreeType.txt": "build/native-geometry-deps/sources/FreeType/LICENSE.TXT",
    "THIRD_PARTY_LICENSES/FriBidi-LGPL-2.1.txt": "build/native-geometry-deps/sources/FriBidi/COPYING",
    "THIRD_PARTY_LICENSES/HarfBuzz.txt": "build/native-geometry-deps/sources/HarfBuzz/COPYING",
    "THIRD_PARTY_LICENSES/libass-ISC.txt": "build/native-geometry-deps/sources/libass/COPYING",
    "THIRD_PARTY_LICENSES/libunibreak-Zlib.txt": "build/native-geometry-deps/sources/libunibreak/LICENCE",
    "THIRD_PARTY_LICENSES/zlib.txt": "build/native-geometry-deps/sources/zlib/LICENSE",
    "THIRD_PARTY_LICENSES/HoshiDicts-GPL-3.0.txt": "vendor/hoshidicts/LICENSE",
    "THIRD_PARTY_LICENSES/HoshiDicts-glaze-MIT.txt": "vendor/hoshidicts/external/glaze/LICENSE",
    "THIRD_PARTY_LICENSES/HoshiDicts-kanji-processor.txt": "vendor/hoshidicts/external/kanji-processor/LICENSE",
    "THIRD_PARTY_LICENSES/HoshiDicts-libdeflate-MIT.txt": "vendor/hoshidicts/external/libdeflate/COPYING",
    "THIRD_PARTY_LICENSES/HoshiDicts-unordered_dense-MIT.txt": "vendor/hoshidicts/external/unordered_dense/LICENSE",
    "THIRD_PARTY_LICENSES/HoshiDicts-utf8proc-MIT.txt": "vendor/hoshidicts/external/utf8proc/LICENSE.md",
    "THIRD_PARTY_LICENSES/HoshiDicts-utfcpp-BSL-1.0.txt": "vendor/hoshidicts/external/utfcpp/LICENSE",
    "THIRD_PARTY_LICENSES/HoshiDicts-xxHash-BSD-2-Clause.txt": "vendor/hoshidicts/external/xxHash/LICENSE",
    "THIRD_PARTY_LICENSES/HoshiDicts-zstd-BSD-3-Clause.txt": "vendor/hoshidicts/external/zstd/LICENSE",
}
LANGUAGE_PARTS = [
    "lookup_character_policy.js",
    "common.js",
    "deinflection.js",
    "japanese.js",
    "english_yomitan_rules.js",
    "english.js",
    "french_yomitan_rules.js",
    "french.js",
    "german_yomitan_rules.js",
    "german.js",
    "chinese.js",
    "korean.js",
    "registry.js",
]
MAIN_RUNTIME_PARTS = [
    "src/main/00_context_state_paths.js",
    "src/main/05_media_source.js",
    *["src/languages/" + name for name in LANGUAGE_PARTS],
    "src/main/10_subtitle_text_style.js",
    "src/main/12_native_subtitle_hit_layer.js",
    "src/main/15_profile_settings.js",
    "src/main/20_dictionary_manifest.js",
    "src/main/25_import_validation.js",
    "src/main/30_backend_import_worker_lookup.js",
    "src/main/40_legacy_line_precompute.js",
    "src/main/50_overlay_bridge_pause.js",
    "src/main/51_anki_connect.js",
    "src/main/52_anki_card_context.js",
    "src/main/52_anki_templates.js",
    "src/main/53_anki_duplicates.js",
    "src/main/54_anki_media_names.js",
    "src/main/54_anki_note_actions.js",
    "src/main/55_anki_integration.js",
    "src/main/60_overlay_lifecycle_toggle.js",
    "src/main/65_dictionary_manager_window.js",
    "src/main/70_menu.js",
    "src/main/99_bootstrap.js",
]
OVERLAY_RUNTIME_PARTS = [
    "src/languages/lookup_character_policy.js",
    "src/overlay/native_subtitle_hit_layer.js",
    "src/overlay/overlay.js",
]
GENERATED_BANNER = "Generated by scripts/build_plugin.py; do not edit this file directly."
PLUGIN_VERSION_PLACEHOLDER = "__IINATAN_PLUGIN_VERSION__"

def js_raw_template_literal(value: str) -> str:
    # Keep String.raw safe: escape template delimiters/interpolation.
    return value.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")

def plugin_version() -> str:
    info = json.loads((ROOT / "Info.json").read_text())
    version = str(info.get("version", ""))
    if not re.fullmatch(r"\d+\.\d+\.\d+", version):
        raise SystemExit("Info.json version must use numeric major.minor.patch form")
    return version

def validate_source_manifest() -> None:
    declared = set(MAIN_RUNTIME_PARTS)
    actual = {
        str(path.relative_to(ROOT))
        for path in (ROOT / "src" / "main").glob("*.js")
    }
    actual.update(
        str(path.relative_to(ROOT))
        for path in (ROOT / "src" / "languages").glob("*.js")
    )
    missing = sorted(declared - actual)
    undeclared = sorted(actual - declared)
    if missing or undeclared:
        details = []
        if missing:
            details.append("missing: " + ", ".join(missing))
        if undeclared:
            details.append("undeclared: " + ", ".join(undeclared))
        raise SystemExit("Main runtime source manifest mismatch; " + "; ".join(details))
    if len(MAIN_RUNTIME_PARTS) != len(declared):
        raise SystemExit("Main runtime source manifest contains duplicate paths")

def render_generated_files() -> dict[str, str]:
    validate_source_manifest()
    version = plugin_version()
    main_parts = []
    for relative_path in MAIN_RUNTIME_PARTS:
        source = (ROOT / relative_path).read_text()
        source = source.replace(PLUGIN_VERSION_PLACEHOLDER, version)
        main_parts.append(source.rstrip())
    main = "// " + GENERATED_BANNER + "\n" + "\n\n".join(main_parts) + "\n"

    overlay_dir = ROOT / "src" / "overlay"
    template = (overlay_dir / "overlay.template.html").read_text()
    html = template.replace("{{OVERLAY_CSS}}", (overlay_dir / "overlay.css").read_text())
    overlay_js = "\n\n".join(
        (ROOT / relative_path).read_text().rstrip()
        for relative_path in OVERLAY_RUNTIME_PARTS
    )
    html = html.replace("{{OVERLAY_JS}}", overlay_js)
    html = "<!-- " + GENERATED_BANNER + " -->\n" + html

    manager_dir = ROOT / "src" / "dictionary-manager"
    manager = (
        "<!-- "
        + GENERATED_BANNER
        + " -->\n"
        + (manager_dir / "dictionary-manager.html").read_text()
    )
    return {
        "main.js": main,
        "overlay.html": html,
        "dictionary-manager.html": manager,
    }

def build_files() -> None:
    for relative_path, contents in render_generated_files().items():
        path = ROOT / relative_path
        if not path.is_file() or path.read_text() != contents:
            path.write_text(contents)

def check_generated_files() -> None:
    stale = []
    for relative_path, expected in render_generated_files().items():
        path = ROOT / relative_path
        if not path.is_file() or path.read_text() != expected:
            stale.append(relative_path)
    if stale:
        raise SystemExit(
            "Generated runtime files are stale: "
            + ", ".join(stale)
            + ". Run: npm run build"
        )

EXCLUDED_DIRS = {".git", ".github", "__pycache__", ".pytest_cache", "dist", "vendor", "build"}
EXCLUDED_FILES = {".DS_Store", ".gitignore", ".gitmodules"}
EXCLUDED_SUFFIXES = {".pyc", ".iinaplgz"}

def should_package(path: Path, output: Path) -> bool:
    if path == output:
        return False
    rel = path.relative_to(ROOT)
    if any(part in EXCLUDED_DIRS for part in rel.parts):
        return False
    if path.name in EXCLUDED_FILES:
        return False
    if path.suffix in EXCLUDED_SUFFIXES:
        return False
    return True

def package(output: Path) -> None:
    build_files()
    validate_root_layout(require_backend=True)
    output.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED) as z:
        for rel_name in PACKAGE_FILE_ALLOWLIST:
            path = ROOT / rel_name
            if path.is_file() and should_package(path, output):
                z.write(path, rel_name)
        for archive_name, source_name in NATIVE_LICENSE_FILES.items():
            source = ROOT / source_name
            if not source.is_file():
                raise SystemExit("Missing native dependency license: " + source_name)
            z.write(source, archive_name)
    validate_package(output)

def validate_root_layout(require_backend: bool = False) -> None:
    missing = [name for name in REQUIRED_PLUGIN_FILES if not (ROOT / name).is_file()]
    if require_backend and not (ROOT / "bin" / "iina-hoshi-dicts").is_file():
        missing.append("bin/iina-hoshi-dicts")
    if missing:
        raise SystemExit("Missing required plugin files: " + ", ".join(missing))
    validate_hoshidicts_submodule()
    if require_backend:
        validate_native_backend()

    info = json.loads((ROOT / "Info.json").read_text())
    required_info = {
        "name": str,
        "identifier": str,
        "version": str,
        "entry": str,
        "globalEntry": str,
        "preferencesPage": str,
        "ghRepo": str,
        "ghVersion": int,
    }
    bad = []
    for key, typ in required_info.items():
        if key not in info or not isinstance(info[key], typ):
            bad.append(key)
    if bad:
        raise SystemExit("Info.json is missing or has invalid fields: " + ", ".join(bad))
    if info["entry"] != "main.js":
        raise SystemExit("Info.json entry must be main.js")
    if info["globalEntry"] != "global.js":
        raise SystemExit("Info.json globalEntry must be global.js")
    if info["preferencesPage"] != "preferences.html":
        raise SystemExit("Info.json preferencesPage must be preferences.html")
    if "/" not in info["ghRepo"]:
        raise SystemExit("Info.json ghRepo must be in owner/repo form")
    package_info = json.loads((ROOT / "package.json").read_text())
    if package_info.get("version") != info["version"]:
        raise SystemExit("package.json version must match Info.json version")
    expected_gh_version = int(info["version"].replace(".", ""))
    if info["ghVersion"] != expected_gh_version:
        raise SystemExit(
            "Info.json ghVersion must be the numeric plugin version "
            + str(expected_gh_version)
        )
    generated_main = (ROOT / "main.js").read_text()
    if (
        'const VERSION = "' + info["version"] + '";'
        not in generated_main
    ):
        raise SystemExit("main.js diagnostics version must match Info.json version")
    settings_check = subprocess.run(
        ["node", "tests/profile_settings.test.js"],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    if settings_check.returncode != 0:
        raise SystemExit(
            "Settings/default validation failed: "
            + (settings_check.stderr or settings_check.stdout).strip()
        )

def validate_native_backend() -> None:
    backend = ROOT / "bin" / "iina-hoshi-dicts"
    try:
        result = subprocess.run(
            [str(backend), "version"],
            check=True,
            capture_output=True,
            text=True,
        )
        version = json.loads(result.stdout)
    except (OSError, subprocess.CalledProcessError, json.JSONDecodeError) as error:
        raise SystemExit("Could not inspect native backend: " + str(error))
    geometry = version.get("assGeometry", {})
    expected = {
        "protocol": 1,
        "available": True,
        "patch": "libass-0.17.2-iinatan-unit-ids-v2",
        "observedPlain": True,
        "ffmpeg": "7.0.1",
        "libass": "0.17.2",
        "architecture": "arm64",
    }
    bad = [
        key
        for key, expected_value in expected.items()
        if geometry.get(key) != expected_value
    ]
    if bad:
        raise SystemExit(
            "Native backend has an incompatible ASS geometry capability: "
            + ", ".join(bad)
        )
    dependencies = subprocess.run(
        ["otool", "-L", str(backend)],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.splitlines()[1:]
    non_system = [
        line.strip().split(" ", 1)[0]
        for line in dependencies
        if not line.strip().startswith(("/usr/lib/", "/System/Library/"))
    ]
    if non_system:
        raise SystemExit(
            "Native backend has non-system dynamic dependencies: "
            + ", ".join(non_system)
        )
    source = ROOT / "dist" / "iina-hoshi-dicts-native-source.tar.gz"
    if not source.is_file():
        raise SystemExit(
            "Missing native corresponding-source archive: "
            + str(source)
            + ". Run scripts/package_native_source.sh."
        )
    with tarfile.open(source, "r:gz") as archive:
        names = set(archive.getnames())
        required = {
            "iinatan-native-source/src/native/ass_geometry.cpp",
            "iinatan-native-source/src/native/media_demux.cpp",
            "iinatan-native-source/scripts/build_native_backend.sh",
            "iinatan-native-source/scripts/build_native_geometry_dependencies.sh",
            "iinatan-native-source/native-dependencies.lock.json",
            "iinatan-native-source/NATIVE_RELINKING.md",
            "iinatan-native-source/patches/libass-0.17.2-iinatan-unit-ids.patch",
            "iinatan-native-source/vendor/hoshidicts/CMakeLists.txt",
            "iinatan-native-source/vendor/hoshidicts/src/query.cpp",
            "iinatan-native-source/vendor/hoshidicts/external/glaze/CMakeLists.txt",
            "iinatan-native-source/vendor/hoshidicts/external/zstd/CMakeLists.txt",
            "iinatan-native-source/vendor/hoshidicts/external/unordered_dense/CMakeLists.txt",
            "iinatan-native-source/vendor/hoshidicts/external/libdeflate/CMakeLists.txt",
            "iinatan-native-source/vendor/hoshidicts/external/utf8proc/CMakeLists.txt",
        }
        missing = sorted(required - names)
        if missing:
            raise SystemExit(
                "Native corresponding-source archive is incomplete: "
                + ", ".join(missing)
            )
        forbidden = sorted(
            name
            for name in names
            if "/.git/" in name
            or name.endswith("/.git")
            or "/.build/" in name
            or name.endswith("/.build")
        )
        if forbidden:
            raise SystemExit(
                "Native corresponding-source archive contains build/VCS artifacts: "
                + ", ".join(forbidden[:10])
            )
        lock_member = archive.extractfile(
            "iinatan-native-source/native-dependencies.lock.json"
        )
        if lock_member is None:
            raise SystemExit("Could not read native dependency lock from source archive")
        source_lock = json.load(lock_member)
        for dependency in source_lock.get("dependencies", []):
            archive_name = dependency["url"].rsplit("/", 1)[-1]
            member_name = "iinatan-native-source/upstream/" + archive_name
            member = archive.extractfile(member_name)
            if member is None:
                raise SystemExit(
                    "Native corresponding-source archive is missing " + member_name
                )
            digest = hashlib.sha256(member.read()).hexdigest()
            if digest != dependency["sha256"]:
                raise SystemExit(
                    "Native source archive checksum mismatch for "
                    + dependency["name"]
                )
        for patch in source_lock.get("patches", []):
            member_name = "iinatan-native-source/" + patch["file"]
            member = archive.extractfile(member_name)
            if member is None or hashlib.sha256(member.read()).hexdigest() != patch["sha256"]:
                raise SystemExit(
                    "Native source archive patch checksum mismatch for " + patch["name"]
                )

def validate_hoshidicts_submodule() -> None:
    gitmodules = ROOT / ".gitmodules"
    if not gitmodules.is_file():
        raise SystemExit("Missing .gitmodules; vendor/hoshidicts must be tracked as a submodule")
    text = gitmodules.read_text()
    if "path = vendor/hoshidicts" not in text or "github.com/afn478/hoshidicts" not in text:
        raise SystemExit(".gitmodules must configure vendor/hoshidicts from afn478/hoshidicts")
    required = [
        "vendor/hoshidicts/CMakeLists.txt",
        "vendor/hoshidicts/LICENSE",
        "vendor/hoshidicts/include/hoshidicts/query.hpp",
        "vendor/hoshidicts/include/hoshidicts/lookup.hpp",
        "vendor/hoshidicts/src/query.cpp",
        "vendor/hoshidicts/src/importer.cpp",
    ]
    missing = [name for name in required if not (ROOT / name).is_file()]
    if missing:
        raise SystemExit(
            "HoshiDicts submodule is missing or uninitialized: "
            + ", ".join(missing)
            + ". Run: git submodule update --init --recursive"
        )

def validate_package(path: Path) -> None:
    if not path.is_file():
        raise SystemExit("Package does not exist: " + str(path))
    with zipfile.ZipFile(path, "r") as z:
        names = set(z.namelist())
        missing = [name for name in REQUIRED_PACKAGE_FILES if name not in names]
        missing.extend(
            name for name in NATIVE_LICENSE_FILES if name not in names
        )
        if missing:
            raise SystemExit("Package is missing required files: " + ", ".join(missing))
        forbidden_prefixes = (".git/", ".github/", "build/", "dist/", "vendor/", "src/")
        forbidden = sorted(name for name in names if name.startswith(forbidden_prefixes))
        if forbidden:
            raise SystemExit("Package contains non-runtime files: " + ", ".join(forbidden[:8]))
        info = json.loads(z.read("Info.json").decode("utf-8"))
        for field in ("entry", "globalEntry", "preferencesPage"):
            if info.get(field) not in names:
                raise SystemExit("Package Info.json references missing " + field + ": " + str(info.get(field)))

def main() -> None:
    parser = argparse.ArgumentParser(description="Build iinatan generated runtime files/package.")
    parser.add_argument("--package", type=Path, help="Optional .iinaplgz output path.")
    parser.add_argument("--validate", action="store_true", help="Validate root plugin metadata/layout after building.")
    parser.add_argument("--require-backend", action="store_true", help="Require bin/iina-hoshi-dicts during --validate.")
    parser.add_argument("--validate-package", type=Path, help="Validate an existing .iinaplgz package.")
    parser.add_argument(
        "--check-generated",
        action="store_true",
        help="Fail when generated runtime files differ from their sources.",
    )
    args = parser.parse_args()
    if args.package:
        package(args.package)
    elif args.check_generated:
        check_generated_files()
    else:
        build_files()
    if args.validate:
        validate_root_layout(require_backend=args.require_backend)
    if args.validate_package:
        validate_package(args.validate_package)

if __name__ == "__main__":
    main()
