const childProcess = require("child_process");
const fs = require("fs");
const os = require("os");
const path = require("path");

const root = path.resolve(__dirname, "..");
const dataRoot =
  process.env.IINATAN_DATA_ROOT ||
  path.join(
    os.homedir(),
    "Library/Application Support/com.colliderli.iina/plugins/.data/com.afn478.iinatan",
  );
const binaryCandidates = [
  path.join(root, "bin/iina-hoshi-dicts"),
  path.join(dataRoot, "bin/iina-hoshi-dicts"),
];
const binary = binaryCandidates.find((candidate) => fs.existsSync(candidate));
if (!binary) {
  throw new Error(
    "Missing iina-hoshi-dicts. Build the native backend or install the development plugin first.",
  );
}

const dictionaryRoot = path.join(dataRoot, "dictionaries");
const dictionaryNames = [
  "JMdict",
  "旺文社国語辞典 第十二版",
  "明鏡国語辞典 第三版",
  "大辞泉 第二版",
  "アクセント辞典",
  "Jiten",
  "BCCWJ",
  "JPDBv2㋕",
];
const dictionaryPaths = dictionaryNames
  .map((name) => path.join(dictionaryRoot, name))
  .filter((candidate) => fs.existsSync(candidate));
if (dictionaryPaths.length < 4) {
  throw new Error(
    `Expected installed Japanese dictionaries under ${dictionaryRoot}`,
  );
}

const fixtureDefinitions = [
  {
    id: "tekido",
    word: "適度",
    label: "適度 — structured POS chip",
    description:
      "A compact adjective/noun entry with Oubunsha, Meikyo, Daijisen, frequency, and pitch metadata.",
  },
  {
    id: "kakeru",
    word: "掛ける",
    label: "掛ける — many senses",
    description:
      "A common polysemous verb for checking dense senses, examples, forms, metadata, and scrolling.",
  },
  {
    id: "kangaeru",
    word: "考える",
    label: "考える — rich verb entry",
    description:
      "A common verb with multiple monolingual explanations and structured dictionary content.",
  },
  {
    id: "honoo",
    word: "炎",
    label: "炎 — short headword",
    description:
      "A compact kanji entry useful for headword, reading, pitch, frequency, and multi-entry spacing.",
  },
];

function lookupFixture(definition) {
  const result = childProcess.spawnSync(
    binary,
    [
      "lookup",
      "--max-results",
      "3",
      "--max-glossaries",
      "4",
      ...dictionaryPaths,
      "--",
      definition.word,
    ],
    {
      encoding: "utf8",
      maxBuffer: 32 * 1024 * 1024,
    },
  );
  if (result.error) throw result.error;
  if (result.status !== 0) {
    throw new Error(
      `Lookup failed for ${definition.word}: ${String(result.stderr || "")}`,
    );
  }
  const payload = JSON.parse(result.stdout);
  if (!payload.ok || !Array.isArray(payload.results) || !payload.results.length)
    throw new Error(`No preview results returned for ${definition.word}`);
  return Object.assign({}, definition, { payload });
}

const fixtures = fixtureDefinitions.map(lookupFixture);
const output = [
  "// Generated by scripts/generate_popup_preview_data.js; do not edit by hand.",
  "// The payloads are hardcoded so dev/popup-preview.html works without IINA.",
  "window.IINATAN_POPUP_PREVIEW_FIXTURES = Object.freeze(",
  `${JSON.stringify(fixtures, null, 2)},`,
  ");",
  "",
].join("\n");
fs.mkdirSync(path.join(root, "dev"), { recursive: true });
fs.writeFileSync(path.join(root, "dev/popup-preview-data.js"), output);
console.log(
  `Wrote ${fixtures.length} popup fixtures from ${dictionaryPaths.length} dictionaries.`,
);
